pipeline {
    agent any

    environment {
        DOCKER_LOGIN = credentials('docker-login')
        IMAGE_REPOSITORY = 'rajatrulaniya/inventory-frontend'
    }

    stages {
        stage('Install & Test') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                    sh 'npm test -- --watchAll=false'
                }
            }
        }

        stage('Image building') {
            steps {
                dir('frontend') {
                    sh """
                        docker build -t ${env.IMAGE_REPOSITORY}:v${env.major}-${env.minor}-${env.BUILD_NUMBER} \
                                    -t ${env.IMAGE_REPOSITORY}:${env.GIT_COMMIT} .
                    """
                }
            }
        }

        stage('Image Scanning') {
            steps {
                sh "trivy image --exit-code 1 --severity HIGH,CRITICAL ${env.IMAGE_REPOSITORY}:v${env.major}-${env.minor}-${env.BUILD_NUMBER}"
            }
        }

        stage('Image Upload') {
            steps {
                sh """
                    echo "$DOCKER_LOGIN_PSW" | docker login -u "$DOCKER_LOGIN_USR" --password-stdin
                    docker push ${env.IMAGE_REPOSITORY}:v${env.major}-${env.minor}-${env.BUILD_NUMBER}
                    docker push ${env.IMAGE_REPOSITORY}:${env.GIT_COMMIT}
                """
            }
        }

        // stage('Helm Deploy to EKS') {

        // }
    }
}