pipeline {
    agent any

    environment {
        DOCKER_LOGIN = credentials('docker-login')
        IMAGE_REPOSITORY = 'rajatrulaniya/inventory-frontend'
        ACTIVE_COLOR = ''
        NEW_COLOR = ''
        FIRST_DEPLOYMENT = false
    }

    stages {
        stage('Set Image tags') {
            steps {
                script {
                    env.IMAGE_TAG1 = "v${env.INVENTORY_FRONTEND_MAJOR}.${env.INVENTORY_FRONTEND_MINOR}.${env.BUILD_NUMBER}"

                    env.IMAGE_TAG2 = "${env.GIT_COMMIT}"
                }
            }
        }

        stage('Build & Test') {
            steps {
                dir('frontend') {
                    sh """
                        docker build -t inventory-frontend-tester --target builder .
                        docker run --rm inventory-frontend-tester npm test -- --watchAll=false || exit 1
                    """
                }
            }
        }

        stage('Image building') {
            steps {
                dir('frontend') {
                    sh """
                        echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin 

                        docker build \
                            -t ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1} \
                            -t ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG2} .
                    """
                }
            }
        }

        stage('Image Scanning') {
            steps {
                sh """
                    trivy image \
                        --exit-code 1 --severity HIGH,CRITICAL \
                        ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1}
                """
            }
        }

        stage('Image Upload & Clean') {
            steps {
                sh """
                    echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin 

                    docker push ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1}

                    docker push ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG2}

                    echo "Keeping only latest 4 images for frontend; Removing older ones..."

                    docker images ${env.IMAGE_REPOSITORY} --format "{{.ID}} {{.CreatedAt}}" | sort -r -k2 | awk 'NR>4 {print \$1}' | sort -u | xargs -r docker rmi -f
                """
            }
        }

        stage('Determine Colors') {
          steps {
            script {
              env.ACTIVE_COLOR = sh(script: "set +e; kubectl get svc frontend-service -o jsonpath='{.spec.selector.color}' 2>/dev/null || echo ''", returnStdout: true).trim()

              env.NEW_COLOR = (env.ACTIVE_COLOR == "blue") ? "green" : "blue"

              if (!env.ACTIVE_COLOR) {
                env.FIRST_DEPLOYMENT = true
                env.ACTIVE_COLOR = "blue"
              }
            }
          }
        }

        stage('Helm Deploy to Idle color') {
          steps {
            sh """
                helm upgrade --install inventory-frontend-${env.NEW_COLOR} ./helm-chart/frontend \
                  --set image.tag=${env.IMAGE_TAG1} \
                  --set activeColor=${env.ACTIVE_COLOR} \
                  --set color=${env.NEW_COLOR} \
                  --set backend_host=${env.BACKEND_HOST} \
                  --set backend_port=${env.BACKEND_PORT}
            """
          }
        }

        stage('Check status of new Deployment') {
          steps {
            sh """
              sleep 7
              kubectl rollout status deployment/inventory-frontend-${env.NEW_COLOR} --timeout=2m
            """
          }
          post {
            failure {
              echo "The new deployment failed, COLOR: ${env.NEW_COLOR}"
            }
          }
        }

        stage('Switch Traffic') {
          steps {
            script {
              sh """
                kubectl patch svc frontend-service -p '{"spec":{"selector":{"color":"${env.NEW_COLOR}"}}}'
              """

              if (!FIRST_DEPLOYMENT) {
                sh "kubectl delete deployment inventory-frontend-${env.ACTIVE_COLOR} || true"
              }
            }
          }
        }
    }
}