pipeline {
    agent any

    environment {
        DOCKER_LOGIN = credentials('docker-login')
        IMAGE_REPOSITORY = 'rajatrulaniya/inventory-backend'
    }
    
    stages {
        stage('Install and Test') {
            steps {
                dir('backend') {
                    sh "mvn dependency:go-offline -B"
                    sh "mvn test"
                }
            }
        }

        stage('Set Image tags') {
            steps {
                script {
                    env.IMAGE_TAG1 = "${env.IMAGE_REPOSITORY}:v${env.INVENTORY_BACKEND_MAJOR}.${env.INVENTORY_BACKEND_MINOR}.${env.BUILD_NUMBER}"

                    env.IMAGE_TAG2 = "${env.IMAGE_REPOSITORY}:${env.GIT_COMMIT}"
                }
            }
        }

        stage('Image Build') {
            steps {
                dir('backend') {
                    sh """
                        echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin

                        docker build \
                            -t ${env.IMAGE_TAG1} \
                            -t ${env.IMAGE_TAG2} .
                    """
                }
            }
        }

        stage('Image Scanning') {
            steps {
                sh """
                    trivy image \
                        --severity HIGH,CRITICAL \
                        ${env.IMAGE_TAG1}
                """
            }
        }

        stage('Image Upload & Clean') {
            steps {
                sh """
                    echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin 

                    docker push ${env.IMAGE_TAG1}

                    docker push ${env.IMAGE_TAG2}

                    echo "Keeping only latest 4 images for frontend; Removing else (only frontend images will be removed)"

                    docker images ${env.IMAGE_REPOSITORY} -q | tail -n +5 | sort -u | xargs -r docker rmi -f
                """
            }
        }
    }
}