pipeline {
    agent any

    environment {
        DOCKER_LOGIN = credentials('docker-login')
        IMAGE_REPOSITORY = 'rajatrulaniya/inventory-backend'
    }
    
    stages {
        stage('Set Image tags') {
            steps {
                script {
                    env.IMAGE_TAG1 = "v${env.INVENTORY_BACKEND_MAJOR}.${env.INVENTORY_BACKEND_MINOR}.${env.BUILD_NUMBER}"

                    env.IMAGE_TAG2 = "${env.GIT_COMMIT}"
                }
            }
        }

        stage('Update CORS') {
          steps {
            dir('backend') {
              sh "sed -i 's|FRONTEND_HOST:FRONTEND_PORT|${env.FRONTEND_HOST}:${env.FRONTEND_PORT}|' src/main/resources/application.properties"
            }
          }
        }

        stage('Build & Test') {
            steps {
                dir('backend') {
                    sh """
                        docker build -t inventory-backend-tester --target builder .
                        docker run --rm inventory-backend-tester mvn test || exit 1
                    """
                }
            }
        }

        stage('Image Build') {
            steps {
                dir('backend') {
                    sh """
                        echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin

                        docker build \
                            -t ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1} \
                            -t ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG2} .
                    """
                }
            }
        }

        stage('Image Scanning') {
            steps {
                sh """
                    trivy image \
                        --severity HIGH,CRITICAL \
                        ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1}
                """
            }
        }

        stage('Image Upload & Clean') {
            steps {
                sh """
                    echo "${env.DOCKER_LOGIN_PSW}" | docker login -u "${env.DOCKER_LOGIN_USR}" --password-stdin 

                    docker push ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG1}

                    docker push ${env.IMAGE_REPOSITORY}:${env.IMAGE_TAG2}

                    echo "Keeping only latest 4 images for backend; removing older ones..."

                    docker images ${env.IMAGE_REPOSITORY} -q | sort -u | tail -n +5 | xargs -r docker rmi -f
                """
            }
        }

        stage('Helm Deploy to EKS') {
          steps {
            sh """
                helm upgrade --install inventory-backend ./helm-chart/backend \
                  --set image.tag=${env.IMAGE_TAG1} \
                  --set db_host="${env.INVENTORY_DB_HOST}"             
            """
          }
        }
    }
}