apiVersion: v1
kind: Service

metadata:
  name: frontend-service

spec:
  type: NodePort
  selector:
    app: inventory-frontend
    color: ""
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080