apiVersion: v1
kind: Service

metadata:
  name: backend-service

spec:
  type: NodePort
  selector:
    app: inventory-backend
    color: ""

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081