apiVersion: apps/v1
kind: Deployment
metadata:
  name: "inventory-frontend-{{ .Values.color }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
        color: {{ .Values.color }}
    spec:
      containers:
        - name: inventory-frontend-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: "inventory-app-config-frontend-{{ .Values.color }}"
                  key: backend_host

            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: "inventory-app-config-frontend-{{ .Values.color }}"
                  key: backend_port