apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
        - name: inventory-frontend-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
